#include <stdio.h>
#include <rpc/rpc.h> //needed for rpc
#include "msg.h" //generated by rpcgen


char **
assignmessage_1_svc(char **msg,  struct svc_req *rqstp)
{
	 char IP[256] = "IP";
	 char TCP[256] = "TCP";

	printf("Message from client: %s\n",msg[0]);
	static char *result; /* must be static! */
	if(strcmp(msg[0],IP)==0 || strcmp(msg[0],TCP)==0){
		result = "OK";
	}
	else{
		result = "NO";
	}
	return (&result);
}