#include  <stdio.h>
#include  <rpc/rpc.h>  /* standard RPC include file */
#include  "msg.h"   /* this file is generated by rpcgen */
main(argc, argv)
   int argc;
   char *argv[];
   {
     CLIENT  *cl; /* RPC handle */
     char    *server;
	 char **sresult; /* return value from str_date_1() */
     if (argc != 2) {
             fprintf(stderr, "usage: %s hostname\n", argv[0]);
			 exit(1);}
     server = argv[1];
	   /*
		Create the client "handle."
		*/
		if ( (cl = clnt_create(server, ASSIGNPROG, ASSIGNMESSAGEVERS, "udp")) == NULL) {
		/*
				* Couldn't establish connection with server.
				*/
				clnt_pcreateerror(server);
				exit(2);
		}
	 
	   char buffer[256];
	   for(;;){ //server always listening
		printf("Message to server: ");
		bzero(buffer,256);
		fgets(buffer,255,stdin);
		buffer[strlen(buffer) - 1] = 0;//trithe new line char
		char *msg[] = {buffer};
		if ( (sresult = assignmessage_1(msg, cl)) == NULL) {
			clnt_perror(cl, server);
			exit(4);
		}
		  printf("Message from host %s = %s\n", server, *sresult);
	   }
		  clnt_destroy(cl);
		  /* done with the handle */
		exit(0);}
